### ISSUE TITLE
add legend in graph

### ISSUE THREAD

**Issue by plibeau** [ovh/tat-contrib#3]
Hi,

Can you add legend in graph when you have multiple of line in one graph ?

https://codeyellowbv.github.io/chartist-plugin-legend/

Example :
new Chartist.Line('.ct-chart-line', {
    labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    series: [
        [12, 9, 7, 8, 5],
        [2, 1, 3.5, 7, 3],
        [1, 3, 4, 5, 6]
     ]
}, {
    fullWidth: true,
    chartPadding: {
        right: 40
    },
    plugins: [
        Chartist.plugins.legend({
            legendNames: ['Blue pill', 'Red pill', 'Purple pill'],
        })
    ]
});

Thx

**Comment by yesnault** [comment]
fixed on https://github.com/ovh/tatwebui-plugin-dashingview

Usage: add a label with "widget-data-legendNames:AAA,BBB,CCC"
